// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"
)

type Querier interface {
	CreateSavingPlan(ctx context.Context, arg CreateSavingPlanParams) error
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetSavingPlan(ctx context.Context, arg GetSavingPlanParams) (SavingGoal, error)
	GetTransaction(ctx context.Context, id string) (TransactionsRecord, error)
	GetUser(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
